### PR TITLE
minor code cleanup, remove an unused declaration

### PR DESCRIPTION
**Pull request by acabrol**

### CODE REVIEW

**Comment by beave** [comment]
There is a bit of transition going on with Sagan and IPC.    I'll apply this ASAP.

**Comment by acabrol** [comment]
Dear Champ,
thank you for your quick feedback.

It was a common work made with Bruno.

As we are using Sagan for our cybersecurity services, it was a just feedback to provide you our contribution.

Kind regards,
Alexandre CABROL PERALES
Sopra Steria I2S
B.U. Cybersecurity
Strategy & Innovation

Le 23 Dec 2015 ? 16:58, Champ Clark <notifications@github.com<mailto:notifications@github.com>> a ?crit :


There is a bit of transition going on with Sagan and IPC. I'll apply this ASAP.

-

**Comment by beave** [comment]
That's great to hear.  Please let me know if you have any questions & appreciate the contribution.

**Comment by beave** [comment]
Keep in mind,  Sagan 1.0.1 at http://sagan.io is considered "stable".   This is my dev. branch.  The dev branch is typically pretty stable,  but just keep that in mind.  Thank you.

**Comment by acabrol** [comment]
Hi, Do you mean we are not making PR on the correct branch?

BTW, I don't see the 1.0.1 branch you mention on GitHub, is it on another repo?


Alexandre CABROL PERALES
Strategy & Innovation – Innovation Lab Responsible
Infrastructure and Security Services

[SOPRA STERIA logo mail]
Sopra-Steria - Bât. EOLIS 2 - Parc Saint-Exupéry
8 avenue Yves Brunaud
BP 90133
31772 Colomiers Cedex – France
Phone : +33 (0)5 34 35 00 00 - Mobile: +33 (0)6 77 72 47 75
alexandre.cabrol@soprasteria.com<mailto:alexandre.cabrol@soprasteria.com> – www.soprasteria.com<http://www.soprasteria.com/>



De : Champ Clark [mailto:notifications@github.com]
Envoyé : 23 December 2015 22:03
À : beave/sagan
Cc : Alexandre CABROL PERALES
Objet : Re: [sagan] minor code cleanup, remove an unused declaration (#62)


Keep in mind, Sagan 1.0.1 at http://sagan.io is considered "stable". This is my dev. branch. The dev branch is typically pretty stable, but just keep that in mind. Thank you.

**Comment by beave** [comment]
I intended this branch to be stable fairly soon.   It will likely be version 1.1.0.   Sagan now uses IPC and on disk memory to "store" flowbits,  threshold, after, etc.   In 1.0.1,   that data would be lost when the Sagan process was stopped.  I have it mostly working, but need to tiddy up some lose ended. 

At that point,  I'll merge in the cleanup and FIFO creation requests.  

I was stating that in production,  version 1.0.1 stable might be best.  That's located at http://sagan.io (https://quadrantsec.com/download/sagan-current.tar.gz to be exact).

If you have any issues,  please let me know.

**Pull request merged**
