### PR TITLE
Simplified version of Sagan_Check_Routing()

### LINKED ISSUE #137: Alerts never trigger if WITH_BLUEDOT not defined
**Describe the bug**
Alerts never trigger if WITH_BLUEDOT is not defined

**To Reproduce**
Configure/build without bluedot.  Then:
```
echo "192.0.2.1|local0|info|info|sshd|2001-01-01|00:00:00|sshd|User ubuntu not allowed because shell /etc/passwd is not executable" >/var/sagan/fifo/sagan.fifo
```

**Expected behavior**
Alert to be triggered

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
In `src/routing.c`, function `Sagan_Check_Routing()` always returns False if WITH_BLUEDOT is not defined.

Simple 2-line fix is possible:

```
--- a/src/routing.c
+++ b/src/routing.c
@@ -93,6 +93,8 @@ bool Sagan_Check_Routing(  _Sagan_Routing *SaganRouting )
                                                                                         }
                                                                                 }
                                                                         }
+#else
+                                                                   ret = true;
 #endif
                                                                 }
                                                         }
```

But IMO it would be better to change the existing logic from deeply-nested to flat.

### PR DESCRIPTION
**Pull request by candlerb**
Fixes #137

Note: I decided not to invert the logic under `/* Flexbit */`. It would look something like this:

```
    if ( rulestruct[SaganRouting->position].flexbit_flag == true &&
            ( rulestruct[SaganRouting->position].flexbit_set_count == false || rulestruct[SaganRouting->position].flexbit_condition_count ) &&
            ( rulestruct[SaganRouting->position].flexbit_set_count == false || rulestruct[SaganRouting->position].flexbit_condition_count == 0 || SaganRouting->flexbit_return == 0 ) &&
            ( rulestruct[SaganRouting->position].flexbit_set_count == true || rulestruct[SaganRouting->position].flexbit_condition_count == 0 || SaganRouting->flexbit_return == 0 ))
        return false;
```

... but I'm not sure that's any better.

### CODE REVIEW

**Comment by beave** [comment]
Had a merge conflict.  However,  Looking at it,  I'm not sure if this will look.  I'll have to look closer.   For example,  if the rulestruct[SaganRouting->position].xbit_flag == false,  we still need to check the underlying options (bluedot, etc).   I'm don't think i can simply return false at that point.   Maybe I'm missing something.   Let me know your thoughts.

Also,  I did a merge of the BLUEDOT fix as well as another with a check_flow issue.

**Comment by candlerb** [comment]
I've rebased it now to avoid the merge conflict.

Effectively the old logic was just one big AND statement:

```
if (foo) {
   if (bar) {
     if (baz) {
        return true;
    }
  }
}
return false;
```

I've turned it the other way round:

```
if (!foo) return false;
if (!bar) return false;
if (!baz) return false;
return true
```

The boolean transforms used are:

not (a and b) = ((not a) or (not b))
not (a or b) = ((not a) and (not b))

I think the new logic is clearer: "if (reason to reject) then return false"

But if I've missed something - i.e. if it's not always a big AND statement as I described above - please let me know.

**Comment by beave** [comment]
I don't think it is.   We test to see is the processor is enabled,  and if it is,  are the results good.   I think it's more like the simplified code below (less nested)   Think of the "flag" as "is this option/processor enabled/disabled".  The "results" would be "it's enabled and we got a positive result". 

if ( foo_flag == false || ( foo_flag == true && foo_results == true ) ) 
  {
  if ( bar_flag == false || ( bar_flag == true && bar_results == true ) ) 
    { 
    return( true );
    }
} 
return(false);


Even if foo_flag is false,  I still need to test bar_flag/bar_results.    If foo_flag is set to true,  then I need to find out if the results where positive.    If they are _not_ positive,  i could  return false.

**Comment by candlerb** [comment]
What my version says is: "if the processor is enabled, and the results from that processor are bad, then return fail"

So if the processor is not enabled, *or* the processor is enabled and the results are good, then it goes onto the next check.  And if they all pass, then the whole lot passes.

I think it should be fairly clear that:

```
if ( foo_flag == false || ( foo_flag == true && foo_results == true ) )
```

simplifies to

```
if ( foo_flag == false || foo_results == true )
```

So your version is:

```
if ( foo_flag == false || foo_results == true ) {
    if ( bar_flag == false || bar_results == true ) {
        if ( baz_flag == false || baz_results == true ) {
            return true;
        }
    }
}
return false;
```

Mine is:

```
if ( foo_flag == true && foo_results == false )
    return false;
if ( bar_flag == true && bar_results == false )
    return false;
if ( baz_flag == true && baz_results == false )
    return false;
return true;
```

"If the XXX test is enabled, and the XXX test returns a fail, then fail everything"

The two aversions re logically identical - and both do short-circuit evaluation. That is, the first test which fails causes the entire function to return false, skipping all further tests.

**Comment by beave** [comment]
Okay.  That makes sense.    Let me test..   I do agree,  it's a lot more simple.    I think I was just already stuck in my logic so it was good to have you come along.

**Comment by beave** [comment]
There's a few issues but I think they can be worked out.    Bluedot was broken (ip lookups) but for a reason that I wouldn't expect you to know.   I think the constant returning of "false" breaks things.  If you look in the engine,  there is this:

if ( Sagan_Check_Routing( SaganRouting ) == true )  
{

/* Check's thresholding, etc....  Got into alerting...

}

Since we return "false" it pretty much breaks almost all rules.  That is,  rules that do not use GeoIP, Bluedot, etc seem to break.  I'll look more later.   I think its a good approach just needs a little more work. 

I'll continue working on it and let me know your thoughts.  Thanks again.

**Comment by beave** [comment]
Actually.. thinking about it,  I think it's just one of the "if's" is off.    Again,  I think this will work fine.  Just have to tweak it a bit more.

**Comment by beave** [comment]
Ok.. just FYI,  i'm back home.   I'm going to start working on this one today...

**Pull request merged**
