### PR TITLE
* Added IPv6 Support

### PR DESCRIPTION
**Pull request by kshelton**
* Expose normalized fields to json output
* Support for files as unix sockets
* Add variable to track finished threads
* Added selector for multi-tenant environment tracking
* (Bug) Memory Leak - Strip_Chars
* (Bug) Uninitialized Stack Variables - DNS_Lookup

### CODE REVIEW

**Comment by kshelton** [comment]
Some notes
- Unified2 output doesn't really support ipv6 in it's current state.  Still need to build a fake ipv6 packet.
- Bluedot compiles but is untested
- Changes to redis compile, but are untested and may not be inline with your design
- Blacklist compiles but is not tested

**Comment by beave** [comment]
Thank you.   Let me review and get back with you.   I'll be able to review in depth tomorrow.

**Comment by beave** [comment]
I've had a bit of time to review.  Most of it looks really good and pretty straight forward.  One thing that I'm having a hard time groking is the "selector" (config->selector_name).  I'm confused about it's use cases.  Could you give me a quick example?  

Also,  does any of this address https://github.com/beave/sagan/issues/71 ?  We are working on an internal solution with this issue but would love to share notes.   

I'll continue poking around.  Thank you.

**Comment by kshelton** [comment]
Re #71 - Unfortunately not.  Haven't had a chance to think through a good solution yet.  I have just avoided creating rules where it would be an issue.  

In regards to the selector, imagine a case where you have sagan receiving data from an aggregating log server.  There is no guarantee that the IP, hostname, or username exist in the same network (or customer).  For example, two different sites could both have a 192.168.1.16.  In this case, all the tracking rules will have an undefined behavior.  By tagging the logs, and using this tag to track, you can now get correctly functioning tracking, even in a multi-tenant environment.

**Comment by kshelton** [comment]
We had a more specific implementation for our deployment scenario, so we tried to generalize it so that it would hopefully be useful for inclusion :)

**Comment by kshelton** [comment]
Another bug I forgot to add to the commit message:  The reason that I changed strtok_r to strsep in the message producing loop is to allow for empty fields (strtok_r treats multiple delimiters as a single delimiter)

**Comment by beave** [comment]
Ok.. I understand now.  I didn't think it dealt with the xbit/thread sync issue.   We are working on something, but it's going to take a lot of work.

Right now,  I'm trying to track back an issue where ip_src/ip_dst in the processors/engine.c gets incorrectly set.  It's leads to these errors:

[W] Warning: Got a getaddrinfo() error for "" but continuing...

I'm not exactly sure why but seems to be something to do with the PR (?).    Anyways, more testing :)

**Comment by beave** [comment]
I think it's coming from parsers/ip.c but I'll need to debug more.

**Comment by kshelton** [comment]
You will get that if IP2Bit is called with an invalid IP.  Can you provide me your test log lines so I can see if I missed something?

**Comment by kshelton** [comment]
I found several issues with Parse_IP.  I had thought it was being tested, but it turns out all my test log lines were hitting normalization rules.  I'm in the process of fixing it and should have an update tomorrow.

**Comment by beave** [comment]
No worries.   I originally thought it might be a incorrect call to IP2Bit from a processor but after disabling all processors,   the error was still coming up.   I tracked it back to Parse_IP as well,  but didn't get any further than that. 

Thanks for looking into it!

**Comment by kshelton** [comment]
Pushed updates.  One thing I noticed is that Parse_IP (the update and the previous way) can be very expensive and was being redone for every rule that asked for it.  I added a cache of this to short circuit and this should cause a pretty decent performance speedup where there are many rules loaded that attempt to parse out the IP.

**Comment by kshelton** [comment]
Another thing I see when I'm looking at the code is that Normalize_Liblognorm is called for every rule that asks for it, instead of at most once per event.  Is there any reason for this I'm missing? Especially now with the single normalize file, I think it can just be called once per event.

**Comment by beave** [comment]
Hmmm. Might legacy left over from where you could use multiple lognorm files.  I'll look asapOn Aug 4, 2017 5:52 PM, kshelton <notifications@github.com> wrote:Another thing I see when I'm looking at the code is that Normalize_Liblognorm is called for every rule that asks for it, instead of at most once per event.  Is there any reason for this I'm missing? Especially now with the single normalize file, I think it can just be called once per event.

**Comment by beave** [comment]
I'll test tonight.  I'm on vacation with my family but will try to look this over and start testing tonight.  thanks man

**Comment by beave** [comment]
Back from vacation.  Check this out now.  You've been busy! :)

**Comment by beave** [comment]
I looked over the liblognorm move & I'm a bit confused.  

Typically,  we only call liblognom if the log line matches the signature criteria and if the rule/signature and has "normalize" rule option enabled.
 
if ( rulestruct[b].normalize == 1 )   /* Is log normalization enabled in the rule */

By moving this up,  it will force all data through liblognorm regardless if the rule option is enabled and regardless if it matches the rules criteria.    Unless I'm missing something (?).  I'll keep poking around.

**Comment by kshelton** [comment]
So, the way it was previously it would normalize once per every rule that it matched the initial criteria, but the normalization wouldn't change so this was duplicated work.  Thinking about it now, the better thing would be to have a flag that indicates if normalization has been done and not redo it.  So it would only happen IFF at least one rule that matched initial criteria wanted it, but not more than once.  I'll move it back and add the flag.

Also, I am tracking down a bug in Parse_IP with the cache for ipv6 in certain cases.  Hope to have a fix soon.

**Comment by beave** [comment]
OK! After pondering on it a little bit,  I certainly do see what you are saying! 

I believe moving it back and adding a "liblognorm_complete" flag (or whatever) would be best.   This way,  if the log message has zero hits then liblognorm is not called.  You could probably do something like:

if ( rulestruct[b].normalize == true && liblognorm_complete == false ) {

/* Do liblognorm stuff */

liblognorm_complete = true; 

}

Nice Catch man!

**Comment by beave** [comment]
I'm running this in dev right now.   Looks good so far.  I still have more review to do, but just wanted to let you know.  I see some compile issues with Bluedot,  but I can hardly blame you for that.  If you can hit me up outside of github,  I'll get you an Bluedot API key for testing.

**Comment by beave** [comment]
Hey hey.  Hope you had a good weekend.   Testing looked pretty good,  but I need to test it against more data.   Had a couple of questions. 

1.  You mentioned a bug in Parse_IP,  did you get to that? 
2.  I noticed tools/sagan-peek.c is failing to build.   I think this is due to a missing #ifdef in the sagan.h (?)
3.  I noticed in rules.c you made some mods to the flow check stuff.  Did you get a chance to check that.  If not,  I'll test against 1.1.8 and this patch. 

I can likely take care of number 2 and 3 if you are swamped.  

Thank you.   I'll continue testing.

**Comment by beave** [comment]
Oh - about bluedot, I'll get you that API key ASAP.   The guy that can help me with that is out today.  He will be back tomorrow.

**Comment by kshelton** [comment]
1. Yes, the wrong size was being passed to Parse_IP from the processors (size in bits instead string size)
2. Just pushed a fix for this
3. Only change was from strtok_r to strsep to allow for empty fields.  I have tested it and seems to cause no issues.

**Comment by beave** [comment]
You rock.  Thanks man.  I'll get you that Bluedot API stuff in the AM.

**Comment by beave** [comment]
Did you get a chance to play with the Bluedot stuff?  If not,  no biggie :)

**Comment by kshelton** [comment]
Not yet, I hope today.

**Comment by kshelton** [comment]
Pushed changes.  Fixed bluedot issues and found that is_inrange was broken as well.  The testing I had done was just coincidentally right.  I believe it is good now.  Also, thoughts on skipping bad rules?

**Comment by beave** [comment]
On the broken rules,. Let's mimic Suricata on that.    Load but warn...  Thanks On Aug 18, 2017 10:15 PM, kshelton <notifications@github.com> wrote:Pushed changes.  Fixed bluedot issues and found that is_inrange was broken as well.  The testing I had done was just coincidentally right.  I believe it is good now.  Also, thoughts on skipping bad rules?

**Comment by beave** [comment]
Still having issues with sagan-peek.c .   I noticed you added libbsd.  Was this to help out with the strlcat/strlcpy issue?  I can look at this later.  

I do need to test flow checking.  This will likely become 1.1.9 once it gets through testing.  I appreciate the additions.

I do have it running in dev right now.   How has it been working for you?

Here's the errors once I remove the libbsd references in the Makefile.  I might just have to bite the bullet and make sagan-peek.c part of the standard build process rather than this kludgy Makefile stuff.

--<snip>--

gcc sagan-peek.c ../src/util-time.c ../src/util.c ../src/parsers/strstr-asm/strstr-hook.c ../src/lockfile.c -I../src -g -D_GNU_SOURCE=1 `pkg-config --cflags libfastjson` -g    -o sagan-peek -lrt `pkg-config --libs libfastjson`
/tmp/ccDFEYz6.o: In function `Between_Quotes':
/home/champ/code/sagan/tools/../src/util.c:343: undefined reference to `strlcat'
/tmp/ccDFEYz6.o: In function `Replace_String':
/home/champ/code/sagan/tools/../src/util.c:447: undefined reference to `strlcpy'
/tmp/ccDFEYz6.o: In function `Var_To_Value':
/home/champ/code/sagan/tools/../src/util.c:614: undefined reference to `strlcat'
/home/champ/code/sagan/tools/../src/util.c:618: undefined reference to `strlcpy'

**Comment by kshelton** [comment]
Yes, on linux you need libbsd to get the strlcpy/strlcat functions.  With libbsd everything works fine, if you have another way to get those functions without it then we can remove it.  Would you like me to merge in the warn on rule errors to this branch?

**Comment by beave** [comment]
Yes on the warning on rule.  We include strlcpy and strlcat if it's not natively available.    There is a strlcat.c and strlcpy.c .  I might make autoconf take care of this nonsense for us .  Don't worry about it right now since I'm looking at reworking the build process on that anyways .On Aug 21, 2017 12:31 PM, kshelton <notifications@github.com> wrote:Yes, on linux you need libbsd to get the strlcpy/strlcat functions.  With libbsd everything works fine, if you have another way to get those functions without it then we can remove it.  Would you like me to merge in the warn on rule errors to this branch?

**Comment by kshelton** [comment]
Great, so I merged in the warnings for rules.  The one thing that I did not handle was duplicate ids, as that's handled after processing all the rules.

**Comment by beave** [comment]
Hello!

libfastjson is really only (json.h) is only really used by liblognorm.   It's possible to compile Sagan without liblognorm support.  With this in mind,  it fails to build in certain situations.   To see what I mean,  run the "build-test.sh" routine.   Do this in your "sagan" directory:

./extra/build-test/build-test.sh

This will attempt to compile with various options enabled.  It helps me identify compile time issue before release.   The ones I'm seeing mostly deal with json.h when liblognorm is disabled.  This is also likely related to the sagan-peek.c compile issues.   Again,  no need to worry about "sagan-peek.h".  I'll take care of that by building a new autoconf/configure.in for it.

I think we're getting close here.

**Comment by beave** [comment]
Yay ! :)

build-test.sh looks good.  Also,  I removed libbsd from string util and added references to util-strlcpy.c and util-strlcat.c . I'll fix that after the merge.  I want to test a couple more things and I think we'll be good to go.   Thanks.

**Comment by beave** [comment]
Hey man, 

Testing showed that addresses are getting reverse with IPv4 in unified2.   I'm thinking this due to the removal of htonl() (?).    

https://github.com/beave/sagan/pull/97/files#diff-b906be1d7276abc1f0c1ba9dd211e714L333

So... if the IP address is "1.2.3.4",  it shows up as "4.3.2.1" in unified2.

**Comment by beave** [comment]
Actually,  you call it htonl() later,  so I'm a bit confused.   Anyways,  I just double checks,  all unified2 is reversing it.

**Comment by kshelton** [comment]
Okay, taking a look

**Comment by kshelton** [comment]
I see the issue, it is because sin_addr/sin6_addr are already in network byte order, let me remove the htonl

**Comment by beave** [comment]
It looks like the src/dst is reverse and always the same as well.    Alerts that I would expect to have a difference source and destination are showing the source in both fields reversed. 

You can probably use u2spew to see what I'm referring too.  Thank you.

**Comment by beave** [comment]
I noted this comment:

// *NOTE*: These will be wrong for IPv6 addresses

Since unified2 doesn't support IPv6,  do you think we should just warn and exit the function when IPv6 is encountered?

**Comment by kshelton** [comment]
We could, but then you would be missing results.  Basically you will only get the lower half in ipv6.  But we can build an ipv6 packet and we could use the extra data portion to put the ipv6 portion into it.  So there are away to provide it but i didn't implement them with this set of changes

**Comment by beave** [comment]
That's a good idea on the extra data.  I hadn't thought of that,  but should have!  From the README.unified2. 

-<snip>-

11              IPv6 Source Address
12              IPv6 Destination Address

-<snip>-

I'm cool with leaving it then and coming back to the extra data functionality.

**Comment by kshelton** [comment]
Yes, I saw it from the source but didn't implement as I don't use unified2 so it wasn't high priority.   I though it would be preferable to have truncated address than lose events, but whichever you prefer. If you want it for inclusion I can see about adding it to the extra data

**Comment by beave** [comment]
No,  I agree with you about the truncated address.   If you could add it to the extra data,  that would be really cool.   We use unified2 here quite a bit.    However,  if you want to do it after this merge,  I'm cool with that too.

**Comment by beave** [comment]
Yes - it's better to not lose events :)

**Comment by beave** [comment]
That fixed the network format/ip reverse issues but the source/destination in unified2 are always the same.   I think what is happening

**Comment by kshelton** [comment]
I have a fix for that, but I am also doing the ipv6 in unified2, give me a few and i'll have it updated.  There were bugs in unified to with size for what was being written in extra data and I missed a htonl.

**Comment by beave** [comment]
No worries.   I got time :)

Hey - I'm still seeing it reverse.  I double checked that I'm running the latest pull and I am (manually looked at the changes).  Here's the alert data from it.

Signature that's tripping: 

alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "[OPENSSH] No identification string - possible scan"; content:"Did not receive identification string"; threshold: type limit, track by_src, count 5, seconds 300; fwsam: src, 1 day; default_proto: tcp; default_dst_port: $SSH_PORT; classtype: network-scan; program: sshd; parse_src_ip: 1; reference: url,wiki.quadrantsec.com/bin/view/Main/5000070; sid: 5000070; rev:6;)

This is the log message:

"Did not receive identification string from 80.82.77.139"

In the unified2 is shows up as a source of  "139.77.82.80:514" -> "139.77.82.80:514"

So it looks like a few problem.   The source/destination are reversed.   It's also reversed in the "extra data".   The destination should have been replaced but wasnt.

However, if I look at the alert.log it looks like this:

[**] [1:5000070] [OPENSSH] No identification string - possible scan [**]
[Classification: network-scan] [Priority: 3] [10.17.1.1]
[Alert Time: 08-22-2017 16:59:29.535999]
2017-08-22 16:59:29 80.82.77.139:514 -> 10.17.1.1:514 auth info
Message:  Did not receive identification string from 80.82.77.139  
[Xref => http://wiki.quadrantsec.com/bin/view/Main/5000070]

If doesn't look like it's honoring the " default_dst_port: $SSH_PORT; " .  However,  that might be a separate issue.

**Comment by kshelton** [comment]
Unified2 should be fixed and now provides a UNIFIED2_IDS_EVENT_IPV6 entry where appropriate.  I did not build a fake ipv6 packet, so that's left to do if you see you need it.  Also, I didn't plumb through a default ipv6 host value so you could end up with an IPv4 address with an IPv6 address.  I handle this in unified2 by just converting the IPv4 to an IPv4 mapped IPv6 address - not sure if that's the best way.

**Comment by beave** [comment]
In unified2 the address is still reversed.    Since you don't really use unified2,  I might need to merge it and correct it myself.   There's also some issues with Redis,  but I figured that was also in my realm.    Considering you have the core working,  It might be easier to merge. 

I have a couple of questions on the "selector".   Are you matching threshold, after, xbits to the "selector" as well?   I just want to make sure I completely understand the selector functionality.

**Comment by kshelton** [comment]
So I run the same rule with log file and get this:

**Comment by beave** [comment]
Ok.. maybe it was me.  Let me re-test.

**Comment by kshelton** [comment]
In regards to selector, yep - xbit, threshold, and after.  I realized the one thing I am not doing is handling track clients, but I was going to wait to deal with that as it seems not critical.  In regards to redis, I'm not surprised.  I took a stab at how it could maybe work for ipv6 but it felt off and hasn't been tested.

**Comment by beave** [comment]
Ok! This is a fun one!  I'll try and explain as best as I can. 

I think we have some data shifting a little bit.  I'm testing with Barnyard2-Extra which we use in production with Sagan 1.1.8,  Snort and Suricata.   This is what I'm seeing when I run this pull.   To start off with,  this is the target event:

>[**] [1:5000070] [OPENSSH] No identification string - possible scan [**]
>[Classification: network-scan] [Priority: 3] [10.17.1.1]
>[Alert Time: 08-30-2017 20:39:20.217824]
>2017-08-30 20:39:20 173.165.207.27:514 -> 10.17.1.1:514 auth info
>Message:  Did not receive identification string from 173.165.207.27
>[Xref => http://wiki.quadrantsec.com/bin/view/Main/5000070]


Right after "Priority:3",  you'll see "10.17.1.1".   This is the original syslog source address.  Just keep that in mind.    Here's the output from u2spew:

> (Event)
>        sensor id: 0    event id: 2     event second: 1504125560        event microsecond: 217824
>        sig id: 5000070 gen id: 1       revision: 6      classification: 36
>        priority: 3     ip source: 173.165.207.27       ip destination: 10.17.1.1
>         src port: 514   dest port: 514  protocol: 6     impact_flag: 0  blocked: 0
>
>Packet
 >       sensor id: 0    event id: 2     event second: 1504125560
 >       packet second: 1504125560       packet microsecond: 217824
 >       linktype: 1     packet_length: 112
>[    0] 00 11 22 33 44 55 00 11 22 33 44 55 08 00 45 00  .."3DU.."3DU..E.
>[   16] 00 62 00 00 00 00 FF 06 38 9D 1B CF A5 AD 1B CF  .b......8.......
>[   32] A5 AD 02 02 02 02 00 00 00 00 00 00 00 00 50 02  ..............P.
>[   48] FF FF 00 00 00 00 20 44 69 64 20 6E 6F 74 20 72  ...... Did not r
>[  64] 65 63 65 69 76 65 20 69 64 65 6E 74 69 66 69 63  eceive identific
>[   80] 61 74 69 6F 6E 20 73 74 72 69 6E 67 20 66 72 6F  ation string fro
>[   96] 6D 20 31 37 33 2E 31 36 35 2E 32 30 37 2E 32 37  m 173.165.207.27
>
>(ExtraDataHdr)
>        event type: 4   event length: 36
>
>(ExtraData)
>        sensor id: 0    event id: 2     event second: 1504125560
>        type: 1 datatype: 1     bloblength: 12  Original Client IP: 173.165.207.27

This looks pretty good,  but notice the "Original Client".  It's 173.165.207.27.  It should be 10.17.1.1 (the original syslog source).   

So we let Barnyard2 do it's thing inserting into the database.   This is what I see from that event:

>+-----------+-----------+
>| ip_src         | ip_dst          |
>+-----------+-----------+
>| 466593197 | 466593197 |
>+-----------+-----------+

Hmmm.. these appear to be the same numbers.  We know the source/destination was different.   When we convert them from a 32 bit int back to octel,  we get "27.207.165.173".  The IP address is reversed. 

In the extra data,  it is this:

>+--------+-----+--------+------+----------+-----+----------------+
>| id     | sid | cid    | type | datatype | len | data           |
>+--------+-----+--------+------+----------+-----+----------------+
>| 547510 |  10 | 664174 |    1 |        1 |   4 | 173.165.207.27 |
>+--------+-----+--------+------+----------+-----+----------------+

I think there's something happening in the unified2 that is causing the records to get a little "off".   Here's my reasoning.   Without changing Barnyard2 (or even stopping it),  this is what happens with this pull request.  

On the other hand,  if I stop the test code and run Sagan 1.1.8 and generate the same event,  it 
records to the database just fine.  That is,  proper source/destination and proper syslog source. 

I would blame barnyard2,  but we don't see this behavior with any version of Sagan,  Snort or Suricata. 

I personally hate unified2,  but I won't even get started on that right now :)

While the u2spew appears to be pretty "close" to correct,  I think it's still off. 

Let me know your thoughts and thanks.

**Comment by kshelton** [comment]
Ok, so the wrong IP was my error due to trying to test sending an IPv6 extra data. I had changed it to ip_src from host and never changed it back. 

In regards to the bytes, they are definitely in network byte order, they are copied right from the sin_addr[6] structure.  If I run something that matches a lot of events, u2spewfoo doesn't get misalligned.  Since unified2 requires network byte order in the format, this should be correct.  

I ran the same test from master and this branch and the only differences were the timestamps.  Can you double check that there isn't something else different between your tests? From what I can tell it should be correct now.

**Comment by beave** [comment]
I'll re-test. Barnyard2 is already running in memory,  so I'm not stopped/restarting that process.   

What I am doing is running the pull 97 code.  I test and look in our SOC console (it's reversed). 

I think run Sagan 1.1.8 and trigger the same signature.   I look in our SOC console and it's "normal". 

The test is pretty straight forward.   Other than the extra data,  it looks pretty "normal" in unified2.

**Comment by kshelton** [comment]
Bah, found it.  I didn't realize barnyard was getting the IP from the packet.  Never changed it after I realized that it need to be in network byte order (which it already was).   On top of that, it was using src for both src and dst.   So, the bad news is that I did not do the work to build a fake ipv6 packet, so ipv6 will still be broken in unified2 until you do that (or pull from the Event unified2 entry instead of the packet).

**Comment by beave** [comment]
ok.  ill test in the AM and thanks man!

**Comment by beave** [comment]
Woo.. the last commit seemed to fix it!  Thanks again.   That was a weird one. 

I'm going to leave it in testing over the weekend.   I'll let you know how it works out.

**Comment by kshelton** [comment]
Great, I'll try and get some time to do the ipv6 packet.  I hate copy paste where it can be avoided so would like to avoid two full functions, but we'll see.

**Comment by beave** [comment]
Could parse_src_ip be getting off?  It seems to work sometimes,  but not others.   For example:


Here's what triggered:

[\*\*] [1:5000022] [OPENSSH] Invalid or illegal user [Brute Force] [10/1] [**]
[Classification: attempted-user] [Priority: 1] [10.17.1.1]
[Alert Time: 08-31-2017 20:12:37.000142]
2017-08-31 20:12:36 **10.17.1.1**:37877 -> **10.17.1.1**:514 auth info
Message:  Failed password for invalid user service from **186.129.250.154** port 37877 ssh2
[Xref => http://wiki.quadrantsec.com/bin/view/Main/5000022]

Here's the rule (with "parse_src_ip: 1")

alert any $EXTERNAL_NET any -> $HOME_NET any (msg:"[OPENSSH] Invalid or illegal user [Brute Force] [10/1]"; pcre: "/invalid user|illegal user/i"; content:!"input_userauth_request"; xbits: set,brute_force,21600; default_proto: tcp; default_dst_port: $SSH_PORT;** classtype: attempted-user; program: sshd; normalize; **parse_src_ip: 1;** parse_port; after: track by_src, count 10, seconds 300; threshold:type limit, track by_src, count 1, seconds 300; reference: url,wiki.quadrantsec.com/bin/view/Main/5000022; sid: 5000022; rev:17;)

Other times, it seems to working okay:

[\*\*] [1:5000070] [OPENSSH] No identification string - possible scan [**]
[Classification: network-scan] [Priority: 3] [10.17.1.1]
[Alert Time: 08-31-2017 20:03:15.322265]
2017-08-31 20:03:15 128.199.112.13:514 -> 10.17.1.1:514 auth info
Message:  Did not receive identification string from 128.199.112.13
[Xref => http://wiki.quadrantsec.com/bin/view/Main/5000070]


alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "[OPENSSH] No identification string - possible scan"; content:"Did not receive identification string";  threshold: type limit, track by_src, count 5, seconds 300; fwsam: src, 1 day; default_proto: tcp; default_dst_port: $SSH_PORT; classtype: network-scan; program: sshd; parse_src_ip: 1; reference: url,wiki.quadrantsec.com/bin/view/Main/5000070; sid: 5000070; rev:6;)

One difference that I do see the "normalize" flag.  The original way it works is,  if "normalize" (liblognorm) fails then "parse_src_ip" will do the work.  If liblognorm is successful,  then we skip parse_src_ip.   It might be related to that?

**Comment by beave** [comment]
Hey - Im looking into the normalize / parse_src_ip thing.  I'll let you know what I find.   It's not related to the  'normalize' and 'parse_src_ip'.  You obviously do the proper checks on that,  so I'm not sure whats up.  I'll let you know.

**Comment by beave** [comment]
So, on my dev box,  it seems to be working fine.  On my test system, it's getting off.  I think this is a local problem (ie - this isn't an issue with your code).  I'm still looking into it. 

I'll figure it out and let it run over the weekend.   If it looks good,  I'll merge Tuesday or Wednesday of next week.   Thanks .

**Comment by kshelton** [comment]
So, I ran it with and without normalize on that rule.  In both cases it worked.  With normalize it hits this: https://github.com/beave/sagan-rules/blob/master/normalization.rulebase#L223 and works and without normalize it parses out correctly and works.  Do you have different versions of liblognorm across boxes?  What is the result if you turn on debug for liglobnorm in sagan?

**Comment by kshelton** [comment]
Also, does it work if you take normalize off that rule?

**Comment by kshelton** [comment]
Also, are you doing a fresh checkout of the branch? At some point I did rebase and squash some commits, it's always possible something could be stale because of that.

**Comment by beave** [comment]
Yep.  It worked fine regardless of the normalize flag.   

This is with a fresh checkout.

**Comment by beave** [comment]
On dev is a fresh copy.  Let me check my test box.  It could be a config issue or something.   In dev is seems pretty solid On Sep 1, 2017 10:17 AM, kshelton <notifications@github.com> wrote:Also, are you doing a fresh checkout of the branch? At some point I did rebase and squash some commits, it's always possible something could be stale because of that.

**Comment by beave** [comment]
Ok .  Looks good in testing as well.   Sorry about that!

I'll let it run for a few days.

**Comment by kshelton** [comment]
Great! Now to get unified2 to send an ipv6 packet and there should be complete ipv6 support

**Comment by beave** [comment]
Do you want to wrap that up in the pull request,  or would you rather I merge next week and then we can start a new one?

**Comment by kshelton** [comment]
I'm thinking a different one unless you have any objections, this PR already has a lot of changes.

**Comment by beave** [comment]
I completely agree.   Let me merge next week after a bit more testing.  I might merge this weekend.  Depends on what the wife wants to do :)

Either way - Yes,  lets start a new pull.

**Comment by kshelton** [comment]
Ha ha, yes I definitely subscribe to the happy wife happy life theory.

**Comment by beave** [comment]
Pretty close to merging this but I'm still having normalization issues on my test system.   Ports and IP addresses are still off.  The "default_dst_port" might have been broken before this,  so I'm not worried about that so much.   The IP addresses are still off.  Here's an example from the alert.log and the rule.

I've upgraded liblognorm & rebuilt Sagan.  I've rebuilt my sagan.yaml as well.  Still,  the same results.  When I get this figured out,  I'll merge.  

Just wanted to give you a heads up.    We have a hurricane headed our way and i've been a bit busy.  :)

>[**] [1:5000016] [OPENSSH] Authentication failure - Brute force [10/1] [**]
>[Classification: unsuccessful-user] [Priority: 1] [10.66.6.149]
>[Alert Time: 09-06-2017 20:40:11.444406]
>2017-09-06 20:40:11 181.25.151.50:44106 -> 10.66.6.149:53 authpriv notice
>Message:  PAM 5 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=181.25.151.50  user=root
>[Xref => http://wiki.quadrantsec.com/bin/view/Main/5000016]


>drop any $EXTERNAL_NET any -> $HOME_NET any (msg:"[OPENSSH] Authentication failure - >Brute force [10/1]"; content: "authentication failure"; xbits: set, brute_force,21600; default_proto: >tcp; default_dst_port: $SSH_PORT; classtype: unsuccessful-user;program: sshd; after: track >by_src, count 10, seconds 300; threshold: type limit, track by_src, count 1, seconds 300; fwsam: >src, 1 day; normalize; parse_src_ip: 1; reference: >url,wiki.quadrantsec.com/bin/view/Main/5000016; sid: 5000016; rev:14;)

**Comment by kshelton** [comment]
Stay safe with the hurricane!  I took a look and I'm not sure it's clear to me.  If I run the message:
>  PAM 5 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=181.25.151.50 user=root
`(Event)
        sensor id: 0    event id: 0     event second: 1504802446        event microsecond: 738503
        sig id: 5000016 gen id: 1       revision: 14     classification: 23
        priority: 1     ip source: 181.25.151.50        ip destination: 172.17.0.1
        src port: 514   dest port: 22   protocol: 17    impact_flag: 0  blocked: 0

Packet
        sensor id: 0    event id: 0     event second: 1504802446
        packet second: 1504802446       packet microsecond: 738503
        linktype: 1     packet_length: 145
[    0] 00 11 22 33 44 55 00 11 22 33 44 55 08 00 45 00  .."3DU.."3DU..E.
[   16] 00 83 00 00 00 00 FF 11 22 D2 B5 19 97 32 B5 19  ........"....2..
[   32] 97 32 02 02 00 16 00 6F 00 00 20 50 41 4D 20 35  .2.....o.. PAM 5
[   48] 20 6D 6F 72 65 20 61 75 74 68 65 6E 74 69 63 61   more authentica
[   64] 74 69 6F 6E 20 66 61 69 6C 75 72 65 73 3B 20 6C  tion failures; l
[   80] 6F 67 6E 61 6D 65 3D 20 75 69 64 3D 30 20 65 75  ogname= uid=0 eu
[   96] 69 64 3D 30 20 74 74 79 3D 73 73 68 20 72 75 73  id=0 tty=ssh rus
[  112] 65 72 3D 20 72 68 6F 73 74 3D 31 38 31 2E 32 35  er= rhost=181.25
[  128] 2E 31 35 31 2E 35 30 20 75 73 65 72 3D 72 6F 6F  .151.50 user=roo
[  144] 74                                               t

(ExtraDataHdr)
        event type: 4   event length: 36

(ExtraData)
        sensor id: 0    event id: 0     event second: 1504802446
        type: 1 datatype: 1     bloblength: 12  Original Client IP: 172.17.0.1
`
That's with fixing the normalization rule (isn't correct in repo).  Seems like default port still works in that case.  Also works with normalization failining.  IPs seem correct (src == 181.25.151.50 dst == sensor).  Not sure where your src port comes from in the post?

**Comment by beave** [comment]
I'm going to merge this.   I've seen some low level stuff that I can fix,  but need to merge it first.  In my "test" system,  i get strange normalization.  In "dev" it works fine.   

I see some other minor issues which I'll start working on.

**Comment by kshelton** [comment]
Great to see you're back after the storm.  Look forward to see the polished fixes.

**Pull request merged**
