### PR TITLE
Add username scope to flexbits

### PR DESCRIPTION
**Pull request by smr1983**
This pull request is related to #163

### CODE REVIEW

**Comment by beave** [comment]
This looks good.  Did you test to make sure the new "username" option to make sure it doesn't interfere with normal flexbit operations?   Also,  if you could update the documentation to reflect this change, that would be great.    That is in the Sagan source tree under do/source/rule-keywords.rst. 

Thank you!

**Comment by smr1983** [comment]
I tested the "username" option extensively, but haven't tested the other options a lot, I will try to test that later this week/beginning next week, that would be just an extension of my test scripts with some additional messages, just have to find some time for that. Is there a standard test set which is used to test the scenario's? Otherwise I will update this pull requests with the rules I used in combination with the messages and the test results.  

I will also try to update the documents also.

**Comment by beave** [comment]
I'll try to test this pull request tomorrow as well.   I don't _think_ it will cause a issue but want to be sure before I merge.   Tomorrow,  i have some JSON testing that i need to do and I'll test standard (non-username) flexbits testing as well.   Sorry,  I don't have any standardized testing at this time.  If need be you can do the documentation in a separate pull .  Whatever is easiest for you.  Thanks again.

**Comment by beave** [comment]
I got a chance to test.   When the "username" is not set (NULL),  it breaks all other usability.  Mostly because your attempting to do strlcpy/memcmp/etc on a NULL value.   For example:  

https://github.com/beave/sagan/pull/164/files#diff-67e9ea62d071a5a170cba1cb2eddbef9R1193

"strlcpy" doesn't play nice with NULL values. 

To save time,  I created these rules for testing:

alert any $HOME_NET any -> $EXTERNAL_NET any (msg: "Flexbit set"; content: "flexbit set"; flexbits: set,testme,3600; classtype: system-event; sid: 5002014; rev:28;)

alert any $HOME_NET any -> $EXTERNAL_NET any (msg: "Flexbit isset"; content: "flexbit isset"; flexbits: isset,by_src,testme; classtype: trojan-activity; sid:5002102; rev:8;)

Then use the "logger" command to "set" or test ("isset"):  For example:

logger "flexbit set"
logger "flexbit isset"

One fix would be to make sure "username" always has something other than NULL in it.  Not sure how I feel about that....   Let me know your thoughts.

**Comment by smr1983** [comment]
Thanks for testing! I indeed haven't tested without usernames... Sorry for missing that and I will try to test more scenario's as soon as possible in my agenda.

Fix username by having a non-null value isn't really clean, but the benefit of that is that the code is almost the same for all statements in the flexbit part. To handle this without setting username to non-null the code becomes much more complicated and will differ substantially from the other cases (by dest, by src etc.). That can be a source of errors with future adjustments of that code.

So in the end I think it is the best solution to always set a username with something other than NULL.

**Comment by beave** [comment]
I agree.   It's not my favorite fix but might be the best way.

**Comment by smr1983** [comment]
I changed the code so that the username null handling is only in flexbit-mmap.c, so that the side effects are minimized.

Please let me know how you think about this change.

I tested this with both the above logger commands and rules and with:

- normalization.rulebase:
version = 2
prefix =
rule=:%[{"type":"json", "name":"."}]%

- rules:
alert any $HOME_NET any -> $EXTERNAL_NET any (msg: "Flexbit username set"; content: "username_set"; normalize; flexbits: set,username_test,3600; classtype: system-event; sid: 5009998; rev:1;)

alert any $HOME_NET any -> $EXTERNAL_NET any (msg: "Flexbit username isset"; content: "username_isset"; normalize; flexbits: isset,username,username_test; classtype: system-event; sid: 5009999; rev:1;)

- logger:
logger {\"username\":\"test\"\,\"username_isset\":\"dummy\"}
logger {\"username\":\"test\"\,\"username_set\":\"dummy\"}

**Comment by beave** [comment]
This looks good to me.  I've merged it. Thank you and sorry for the delay.

**Pull request merged**
