### PR TITLE
Flow checking for ports and protocol with support for port variables - Updated with no conflicts

### PR DESCRIPTION
**Pull request by YoichSec**
Updated with conflicts resolved.
This implements the changes discussed in Issue  #84 

Protocol and Ports at the beginning of each rule are now fields that are checked against messages.

Default protocol and default port options in each rule provide the function previously held by the protocol and ports at the beginning of the rule.

Port ranges and groups are supported in rules and in sagan.yaml in a similar way to port groups in Snort. For example,
IRC_PORTS: "6660-6669,7000"
is a valid port-group entry in sagan.yaml.

The attached test files may help in testing/review.
[SaganYamlPorts.txt](https://github.com/beave/sagan/files/925028/SaganYamlPorts.txt)
[portcheck.txt](https://github.com/beave/sagan/files/925030/portcheck.txt)
[portcheckrules.txt](https://github.com/beave/sagan/files/925029/portcheckrules.txt)

### CODE REVIEW

**Comment by beave** [comment]
Oh - and thank you for the SaganYamlPorts.txt, portcheck.txt and portcheckrules.txt files.  Those will help a lot.

**Comment by YoichSec** [comment]
Sounds good.
For the unused variables...
Line 189,190 src_port and dst_port can be deleted.
The others are unneeded too, but there should be the following lines:
rulestruct[counters->rulecount].default_proto = config->sagan_proto;
rulestruct[counters->rulecount].default_dst_port = config->sagan_port;
rulestruct[counters->rulecount].default_src_port = config->sagan_port;

above the parsing lines:
if (!strcmp(rulesplit, "default_proto"))
if (!strcmp(rulesplit, "default_src_port")) 
if (!strcmp(rulesplit, "default_dst_port")) 

I did something a little weird there. Sorry about that.

**Comment by beave** [comment]
Just a quick update.  I'm doing some functionality testing today.   I'm hoping to merge and make those minor changes today or tomorrow.

**Comment by beave** [comment]
Hey - can you send you normalize rulebase (liblognorm) file over?  In the mean time,  I'll create the ones to play with .  Thanks.

**Comment by YoichSec** [comment]
Here you go.
[normalization.rulebase.txt](https://github.com/beave/sagan/files/959035/normalization.rulebase.txt)

**Comment by beave** [comment]
Did you modify the normalization.rulebase?  The only reason I ask is that I'm having a hard time getting it to normalize the snort data correctly on my dev box.    It could be that my dev box is all mucked up.    

Thanks.

**Comment by beave** [comment]
Bahah.  Nevermind.   It was something I was doing incorrect/poorly :)

I'm good.

**Comment by YoichSec** [comment]
I do recall making a very minor change to the snort rule to make it work with our running version of snort.

**Comment by beave** [comment]
[alert.log.txt](https://github.com/beave/sagan/files/959403/alert.log.txt)

Here's the alert.log from my first run.   When you get a chance,  please look it over and see if it looks normal to you.   I'm doing the same on my side.   Thanks.

**Comment by YoichSec** [comment]
Hmm... the results are not as expected. The rules are set up so you should see 74 alerts:
[YOICHTEST] 1... through [YOICHTEST] 74

Also, [YOICHTEST] 0 ... rules should not trigger. They are specifically set up to test fail conditions. 

I have it working as expected in my setup, but I can take another look if you'd like. I don't have a large block of time until after Friday though.

**Comment by beave** [comment]
No rush.  Let me make sure I'm not messing up something on the testing myself.   I can give you a copy of my testing scripts.

**Comment by beave** [comment]
I've tried the code a couple of different ways.   First off,  just to be clear,  I'm using the code associated (without modification) from this pull request.  I only bring that up because we discuss some minor code modifications earlier.   I tried to also incorporate those changes into the pull request but the results were the same (which isn't surprising).  

I'm including the sagan.log,  alert.log and fast.log for debugging.   Maybe I've missed something?  The sagan.log is with "--debug syslog,normalization" enabled.  This way you can see the data Sagan is being given (raw log data) and how it's being normalized.  

There's no rush on this.   Just wanted to get you the data while I can.  I think it's pretty close! 

Thank you.

[fast.log.txt](https://github.com/beave/sagan/files/959543/fast.log.txt)
[alert.log.txt](https://github.com/beave/sagan/files/959544/alert.log.txt)
[sagan.log.txt](https://github.com/beave/sagan/files/959545/sagan.log.txt)

**Comment by beave** [comment]
Hello, 

Did you have a chance to look at this yet?   Thanks.

**Comment by YoichSec** [comment]
I'll be looking at it today. Sorry for the delay.

**Comment by beave** [comment]
All good man.   Just curious :)

**Comment by YoichSec** [comment]
So as a simple test, I cloned my forked repo from which the pull request was created into a new directory and re-ran the file. I got the expected results of all 74 test cases passed with nothing unexpected triggering. Could we maybe compare notes on sagan.yaml? 
Here's mine for testing purposes.
[sagan.yaml.txt](https://github.com/beave/sagan/files/969065/sagan.yaml.txt)

**Comment by beave** [comment]
sure thing...  What I'll do is run with your .yaml tonight.   Thanks.  Will let you know how it turns out.

**Comment by beave** [comment]
Ok.  There must be something wrong with my testing method.  I've run,  with your config (only changed the FIFO & enabled fast.log) and still get the same results.  I've attached the sagan.log,  which shows that normalization appears to be working fine.   

[sagan.log.txt](https://github.com/beave/sagan/files/969114/sagan.log.txt)

Here's what was triggered: 

[alert.log.txt](https://github.com/beave/sagan/files/969115/alert.log.txt)
[fast.log.txt](https://github.com/beave/sagan/files/969116/fast.log.txt)

Here's my testing scripts.  They basically replay the logs through the "logger" command with the program of "snort".    Here's the shell script

[yoichsec-inject.sh.txt](https://github.com/beave/sagan/files/969118/yoichsec-inject.sh.txt)

It reads in the this file (the logs you supplied):

[yoichsec-logs.txt](https://github.com/beave/sagan/files/969119/yoichsec-logs.txt)

I'll move this to a fresh Ubuntu box at Digital Ocean tonight and re-run the tests.   I'll let you know the results.   Please take a look at my output and scripts.   Perhaps I'm missing something somewhere?   What's confusing,  the normalization in the sagan.log looks solid :(

Ok - Testing on a fresh ubuntu box....

**Comment by beave** [comment]
I booted a new/fresh Ubuntu 16.04 box at Digital Ocean and repeated my test.   The results are about the same.   I've attached my alert.log and fast.log.   IMHO this can only mean a couple of things:  1 -  The way i'm testing it is incorrect.   2 - Somehow the code got out of sync? 

Do you want access to my Ubuntu test platform?  It's completely fresh Ubuntu box.   Can you test my scripts with your code base and see if you get the same or different results? 

Sorry but I'm having difficulty get the same results.   Thanks.

[fast.log.txt](https://github.com/beave/sagan/files/969345/fast.log.txt)
[alert.log.txt](https://github.com/beave/sagan/files/969346/alert.log.txt)

**Comment by YoichSec** [comment]
I tried your test method with the script and still got the expected results. We must be running different code somehow. I could manually go through the updates. Do you want to give a quick go at cloning my fork and checking the results with that?

**Comment by beave** [comment]
i cloned from https://github.com/YoichSec/sagan and re-ran the test.   Still seeing this:

[**] [1:4000212] [YOICHTEST] 0 Port Test NOT 80 - Should NOT Trigger for Src Port 80 [**]
[**] [1:4000230] [YOICHTEST] 0 Portvar Test Range - Should NOT Trigger for Src Port 65535 [**]

I'm going to e-mail you access to my test box off the list.    I think we're getting out of sync somehow.

**Comment by beave** [comment]
Just e-mailed you credentials to this temp box.  Maybe if we can get on the same hardware,  we can figure out were we are getting out of sync.

**Comment by YoichSec** [comment]
OK it looks like it's working on your test box now. I added some debug output to check-flow.c (right on the box) but nothing functional. In the end, it was a normalization issue. I needed to make the subtle change to the snort rule.

**Comment by beave** [comment]
I knew it was going to be something like that.  What ended up being the subtle change (out of curiosity). 

Thanks for the extra effort.  I'll heck it out in a few minutes.

**Comment by YoichSec** [comment]
image
Aside from source and destination being switched for some reason, there's also a colon after priority in the snort events I get from Security Onion. I should have included the normalization changes when I attached the rest of the test. My bad.

**Comment by beave** [comment]
This looks awesome man.  I've tested a good bit and I think we are good.  Sorry it had to be so painful :)  I'm going to add those normalization rulebase into the Sagan back end as well.  

Thanks - I'll merge later tonight.

**Comment by beave** [comment]
Just FYI.  We are running the code in testing and I've modified the github.com Sagan Rules with the necessary changes.    So far, so go.  Thanks again and see you at Defcon.

**Comment by YoichSec** [comment]
Great. Thanks for the updates.

**Pull request merged**
